version: "3"
services:
  devops-db:
    image: "postgres:latest"
    container_name: "employees-app"
    environment:
      - POSTGRES_USER=temp
      - POSTGRES_PASSWORD=temp123
      - POSTGRES_DB=employees
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  devops:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - devops-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://devops-db:5432/employees
      - SPRING_DATASOURCE_USERNAME=temp
      - SPRING_DATASOURCE_PASSWORD=temp123
    ports:
      - "9990:9990"

volumes:
  postgres-data:
