apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
  namespace: devops-project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:      
      labels:
        app: devops-app
    spec:
      containers:
      - name: devops
        image: evgenijapopchan/devops-project:latest
        ports:
        - containerPort: 9990
        envFrom:
        - configMapRef:
            name: app-config
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://devops-db:5432/employees
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: POSTGRES_USER
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: config-volume
          mountPath: /config
      volumes:
      - name: config-volume
        configMap:
          name: app-config